name: Build and Release

on:
  workflow_call:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: dist

    - name: Extract package version
      id: package_version
      run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

    - run: echo v${{ steps.package_version.outputs.version }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package_version.outputs.version }}
        release_name: Release v${{ steps.package_version.outputs.version }}
        body: Release notes for v${{ steps.package_version.outputs.version }}
    
    - run: |
        zip -r dist.zip dist/*

    - name: Upload Release Artifact
      if: github.ref == 'refs/heads/main'
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist.zip
        asset_name: build-artifact.zip
        asset_content_type: application/gzip
